--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
projects:
  OutiServerSensouPlugin:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.2
        branch: PM4
      - src: HimbeersaftLP/LibSkin/LibSkin
        version: ^2.0.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
      - src: thebigsmileXD/apibossbar/apibossbar
        version: ^0.1.5
        branch: PM4
      - src: KenCir/FormAPI/libFormAPI
        version: ^2.1.0
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0

    lint:
      phpstan: false
...
