--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
projects:
  OutiServerSensouPlugin:
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.0
...
