--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
projects:
  OutiServerSensouPlugin:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI # ユーザー名/リポジトリ名/Virion名
        version: 1.2.0 # バージョン
...
