--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServer-pmmp-plugin
build-by-default: true
branches:
  - master
projects:
  OutiServerSensouPlugin:
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3
    path: ""
    lint: false # うるさいのでfalseに
...
