--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
- develop
projects:
  OutiServerSensouPlugin:
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.0
...
