--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- poggit-CI
projects:
  OutiServerSensouPlugin:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.0.1
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: ^1.0.2
        branch: PM4
      - src: Vecnavium\FormsUI\libFormsUI
        version: ^1.1.1
        branch: master
...
