--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
projects:
  OutiServerSensouPlugin:
    libs:
      - src: CortexPE\DiscordWebhookAPI\DiscordWebhookAPI
        version: ^1.0.2
      - src: poggit\libasynql\libasynql
        version: ^3.4.0
      - src: Vecnavium\FormsUI\libFormsUI
        version: ^1.1.0
    path: ""
...
