--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/OutiServerSensouPlugin
build-by-default: true
branches:
- master
- develop
projects:
  OutiServerSensouPlugin:
    path: ""
    libs:
      - src: Vecnavium\FormsUI\FormsUI
        version: 1.1.0
      - src: CortexPE\DiscordWebhookAPI\DiscordWebhookAPI
        version: 1.0.2
      - src: poggit\libasynql\libasynql
        version: 3.4.0
...
