name: OutiServerSensouPlugin
main: ken_cir\outiserversensouplugin\Main
description: おうちサーバー用プラグイン 戦争
author: Ken_Cir
version: 1.0.0-BETA
api: 4.2.1
mcpe-protocol: 486
extensions:
  - pthreads
  - zip
  - sockets
  - zlib
  - pcntl

permissions:
  outiserver.default:
    description: おうち鯖 デフォルト権限
    default: true
  outiserver.test:
    description: テスト権限
    default: op