name: OutiServerSensouPlugin
main: Ken_Cir\OutiServerSensouPlugin\Main
description: おうちサーバー用プラグイン シーズン11var
author: Ken_Cir
version: 1.0.0-pmmp4
api: 4.0.0

permissions:
  outiserver.default:
    description: おうち鯖 デフォルト権限
    default: true
  outiserver.test:
    description: テスト権限
    default: op