name: OutiServerSensouPlugin
main: ken_cir\outiserversensouplugin\Main
description: おうちサーバー用プラグイン シーズン11var
author: Ken_Cir
version: 1.0.0-BETA
api: 4.0.6
mcpe-protocol: 475
extensions:
  - pcntl
  - pthreads
  - zip
  - curl
  - sockets

permissions:
  outiserver.default:
    description: おうち鯖 デフォルト権限
    default: true
  outiserver.test:
    description: テスト権限
    default: op