---
# プレイヤーの初期所持金
default_player_money: 10000

# アドミンショップの値段変動時に減らす売った数の個数
adminshop_fluctuation_count: 64

# 派閥金庫のデフォルト所持金
faction_default_safe: 11000

# 派閥のデフォルト所持金
faction_default_money: 0

# 土地の値段
land_price: 10000


# --- 自動アップデート設定 ---
# PMMPの自動アップデート・再起動を有効にするか
pmmp_auto_update_enable: true

# このプラグインの自動アップデート・再起動を有効にするか
plugin_auto_update_enable: true


# --- 定期実行系設定 ---
# PMMP・プラグインのアップデートをチェックする間隔(秒)
autoUpdateCheckDealy: 600

# 定期メッセージの間隔(秒)
scheduleMessageDelay: 300

# バックアップをする間隔(秒)
backup_delay: 3600

# 派閥の土地をバックアップする間隔(秒)
world_backup_delay: 3600

# アドミンショップの値段変動を行う間隔(秒)
adminshop_fluctuation_delay: 3600

# --- ---
# サーバー関係ログを出力するWebhookURL
Discord_Server_Webhook: ""

# エラーログを出力するWebhookURL
Discord_Error_Webhook: ""

# プラグインログを出力するWebhookURL
Discord_Plugin_Webhook: ""

# Playerログを出力するWebhookURL
Discord_Player_Webhook: ""

# レポート・要望を送信するWebhookURL
Report_Request_Webhook: ""
...