---
# ---バックアップ設定---


# ---Discord関係設定---
# BotのToken
Discord_Bot_Token: ""

# DiscordのサーバーID
Discord_Guild_Id: ""

# DiscordのコンソールチャンネルID
Discord_Console_Channel_Id: ""

# DiscordのマイクラチャットチャンネルID
Discord_MinecraftChat_Channel_Id: ""

# サーバー関係ログを出力するWebhookURL
Discord_Server_Webhook: ""

# エラーログを出力するWebhookURL
Discord_Error_Webhook: ""

# プラグインログを出力するWebhookURL
Discord_Plugin_Webhook: ""

# Playerログを出力するWebhookURL
Discord_Player_Webhook: ""

# レポート・要望を送信するWebhookURL
Report_Request_Webhook: ""
...