---
# ---プラグインメイン設定---
# プレイヤーの初期所持金
default_player_money: 10000

# ---自動アップデート設定---
# PMMPの自動アップデート・再起動を有効にするか
pmmp_auto_update_enable: true

# このプラグインの自動アップデート・再起動を有効にするか
plugin_auto_update_enable: true

# ---定期実行系設定---
# 定期メッセージの間隔(秒) 20tick = 1秒前提
scheduleMessageDelay: 300

# ---Discord関係設定---
# BotのToken
Discord_Bot_Token: ""

# DiscordのサーバーID
Discord_Guild_Id: ""

# DiscordのコンソールチャンネルID
Discord_Console_Channel_Id: ""

# DiscordのマイクラチャットチャンネルID
Discord_MinecraftChat_Channel_Id: ""

# サーバー関係ログを出力するWebhookURL
Discord_Server_Webhook: ""

# エラーログを出力するWebhookURL
Discord_Error_Webhook: ""

# プラグインログを出力するWebhookURL
Discord_Plugin_Webhook: ""

# Playerログを出力するWebhookURL
Discord_Player_Webhook: ""

# レポート・要望を送信するWebhookURL
Report_Request_Webhook: ""
...