name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download DevTools
        run: wget https://github.com/pmmp/DevTools/releases/download/1.14.0/DevTools.phar -O ~/DevTools.phar
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          command: composer install --no-interaction --no-ansi --no-dev
      - name: Build source code
        run: php -dphar.readonly=0 ~/DevTools.phar --make ./ --out ./outiserverpmmpplugin.phar
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: PHAR
          path: ./outiserverpmmpplugin.phar
      - name: Zip output
        run: zip ./cl.zip ./outiserverpmmpplugin.phar
      - name: commit message
        run: echo github.event.head_commit
      - name: file send to discord
        uses: tsickert/discord-webhook@v4.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "CIチェックが終了しました\n簡易ビルドは正常に完了しました\n差分: ${{ github.event.compare}}"
          filename: ./cl.zip
          username: ${{ github.event.sender.login }}
          avatar-url: ${{ github.event.sender.avatar_url }}


