name: Label pull request

on:
  pull_request:
    types:
      - reopened
      - opened
      - closed
      - assigned

env:
  PROJECT_NAME: TODO

jobs:
  issue_labels:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add backlog label
        if: "github.event.action == 'opened'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: Backlog"
          remove-labels: "Status: Closed"
      - name: Add inprogress label
        if: "github.event.action == 'assigned' || github.event.action == 'reopened'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: In Progress"
          remove-labels: "Status: Backlog, Status: Closed"
      - name: Add close label
        if: "github.event.action == 'closed'"
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Status: Closed"
          remove-labels: "Status: Backlog, Status: In Progress"

  move_assigned_card:
    runs-on: ubuntu-latest
    name: Move assigned card
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'assigned'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: 進行中 or 作業中Issue・Pull Request
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: "github.event.action == 'reopened'"
        with:
          project: ${{env.PROJECT_NAME}}
          column: 進行中 or 作業中Issue・Pull Request
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
