name: updateVersion

on: [push]

jobs:
  update:
    name: updateVersion
    if: "startsWith(github.event.head_commit.message, 'updateversion ')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run script
        run: |
          echo ls
      - name: Run script
        run: |
         python updateVersion.py
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          publish_branch: gh-pages